# Generated by Django 6.0.3 on 2026-04-10 18:25

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carteles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ValorTasaAnual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)], verbose_name='Año fiscal')),
                ('valor_m2', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor por m² ($)')),
                ('recargo_iluminado_pct', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Desde 2026: 25%. Años anteriores: 0%.', max_digits=5, verbose_name='Recargo publicidad iluminada (%)')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Valor de tasa anual',
                'verbose_name_plural': 'Valores de tasa anual',
                'ordering': ['-anio'],
            },
        ),
        migrations.CreateModel(
            name='Liquidacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('superficie_m2', models.DecimalField(decimal_places=4, help_text='Copiado del cartel. Editable si el contribuyente objeta la medición.', max_digits=10, verbose_name='Superficie liquidada (m²)')),
                ('es_iluminado', models.BooleanField(default=False, help_text='Si es True y el año >= 2026, se aplica recargo del 25%.', verbose_name='¿Publicidad iluminada?')),
                ('aplica_descuento_ruta63', models.BooleanField(default=False, help_text='Carteles en Ruta 63 desde km 5 en adelante: 30% de bonificación.', verbose_name='¿Aplica descuento Ruta 63?')),
                ('km_ruta63', models.DecimalField(blank=True, decimal_places=2, help_text='Informado por GPS o manualmente en observaciones del cartel.', max_digits=7, null=True, verbose_name='Kilómetro en Ruta 63')),
                ('sobre_ruta2', models.BooleanField(default=False, help_text='Carteles sobre Ruta 2: sin descuento.', verbose_name='¿Está sobre Ruta 2?')),
                ('monto_base_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Suma de subtotales de todos los períodos, sin mora.', max_digits=14, verbose_name='Monto base total ($)')),
                ('monto_mora_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Intereses por mora total ($)')),
                ('monto_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monto base + mora. Es el monto de la deuda actualizada.', max_digits=14, verbose_name='Monto total liquidado ($)')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('notificada', 'Notificada al contribuyente'), ('conformada', 'Conformada (contribuyente de acuerdo)'), ('en_plan', 'En plan de pagos'), ('pagada', 'Pagada'), ('objetada', 'Objetada por el contribuyente')], default='borrador', max_length=20)),
                ('version', models.PositiveIntegerField(default=1, help_text='Se incrementa cada vez que se edita la liquidación.', verbose_name='Versión')),
                ('fecha_determinacion', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de determinación')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('cartel', models.ForeignKey(limit_choices_to={'estado_procesamiento': 'ok', 'estado_registro': 'activo'}, on_delete=django.db.models.deletion.PROTECT, related_name='liquidaciones', to='carteles.cartel', verbose_name='Cartel')),
                ('empresa_publicista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liquidaciones_como_empresa', to='carteles.persona', verbose_name='Empresa publicista (al momento)')),
                ('generado_por', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liquidaciones_generadas', to=settings.AUTH_USER_MODEL, verbose_name='Generado por')),
                ('liquidacion_origen', models.ForeignKey(blank=True, help_text='Si es una revisión, apunta a la liquidación que le dio origen.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisiones', to='tasacartel.liquidacion', verbose_name='Liquidación original')),
                ('propietario_cartel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liquidaciones_como_propietario_cartel', to='carteles.persona', verbose_name='Propietario del cartel (al momento)')),
                ('propietario_terreno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liquidaciones_como_propietario_terreno', to='carteles.persona', verbose_name='Propietario del terreno (al momento)')),
            ],
            options={
                'verbose_name': 'Liquidación',
                'verbose_name_plural': 'Liquidaciones',
                'ordering': ['-fecha_determinacion', '-version'],
            },
        ),
        migrations.CreateModel(
            name='PlanDePago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_suscripcion', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de suscripción')),
                ('monto_deuda_base', models.DecimalField(decimal_places=2, help_text='Snapshot de liquidacion.monto_total al momento de suscribir.', max_digits=14, verbose_name='Deuda base del plan ($)')),
                ('monto_anticipo', models.DecimalField(decimal_places=2, help_text='No paga interés de financiación.', max_digits=14, verbose_name='Anticipo / Cuota 1 ($)')),
                ('cantidad_cuotas', models.PositiveIntegerField(help_text='Cuotas 2..N, todas con interés de financiación.', verbose_name='Cantidad de cuotas (sin contar el anticipo)')),
                ('tasa_financiacion_mensual', models.DecimalField(decimal_places=4, help_text='Interés simple. Ej: 0.04 para 4% mensual.', max_digits=5, verbose_name='Tasa de financiación mensual (fracción)')),
                ('estado', models.CharField(choices=[('vigente', 'Vigente'), ('cumplido', 'Cumplido'), ('caducado', 'Caducado')], default='vigente', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('liquidacion', models.OneToOneField(limit_choices_to={'estado__in': ['conformada', 'en_plan']}, on_delete=django.db.models.deletion.PROTECT, related_name='plan_de_pago', to='tasacartel.liquidacion', verbose_name='Liquidación')),
            ],
            options={
                'verbose_name': 'Plan de pago',
                'verbose_name_plural': 'Planes de pago',
                'ordering': ['-fecha_suscripcion'],
            },
        ),
        migrations.CreateModel(
            name='CuotaPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_cuota', models.PositiveIntegerField(verbose_name='N° de cuota')),
                ('monto_capital', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Capital ($)')),
                ('monto_interes', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Interés ($)')),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Total cuota ($)')),
                ('fecha_vencimiento', models.DateField(verbose_name='Fecha de vencimiento')),
                ('pagado', models.BooleanField(default=False, verbose_name='¿Pagada?')),
                ('fecha_pago', models.DateField(blank=True, null=True, verbose_name='Fecha de pago')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuotas', to='tasacartel.plandepago', verbose_name='Plan de pago')),
            ],
            options={
                'verbose_name': 'Cuota',
                'verbose_name_plural': 'Cuotas',
                'ordering': ['nro_cuota'],
                'unique_together': {('plan', 'nro_cuota')},
            },
        ),
        migrations.CreateModel(
            name='LiquidacionPeriodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio_fiscal', models.IntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)], verbose_name='Año fiscal')),
                ('valor_m2_aplicado', models.DecimalField(decimal_places=2, help_text='Snapshot del valor al momento de la liquidación.', max_digits=12, verbose_name='Valor m² aplicado ($)')),
                ('subtotal_base', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='superficie_m2 × valor_m2_aplicado', max_digits=14, verbose_name='Subtotal base ($)')),
                ('recargo_iluminado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Recargo iluminado ($)')),
                ('descuento_ruta63', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Valor positivo: se resta del subtotal.', max_digits=14, verbose_name='Descuento Ruta 63 ($)')),
                ('subtotal_con_recargos', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='subtotal_base + recargo_iluminado − descuento_ruta63', max_digits=14, verbose_name='Subtotal con recargos ($)')),
                ('meses_mora', models.IntegerField(default=0, help_text='Calculado desde dic. del año fiscal hasta la fecha de determinación.', verbose_name='Meses de mora')),
                ('tasa_mora_mensual', models.DecimalField(decimal_places=4, default=Decimal('0.0400'), help_text='Por defecto 0.04 (4% mensual). Editable para casos especiales.', max_digits=5, verbose_name='Tasa mora mensual (fracción)')),
                ('interes_mora', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='subtotal_con_recargos × meses_mora × tasa_mora_mensual', max_digits=14, verbose_name='Interés por mora ($)')),
                ('total_periodo', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='subtotal_con_recargos + interes_mora', max_digits=14, verbose_name='Total del período ($)')),
                ('liquidacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodos', to='tasacartel.liquidacion', verbose_name='Liquidación')),
                ('valor_tasa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='periodos_liquidacion', to='tasacartel.valortasaanual', verbose_name='Valor de tasa del año')),
            ],
            options={
                'verbose_name': 'Período liquidado',
                'verbose_name_plural': 'Períodos liquidados',
                'ordering': ['anio_fiscal'],
                'unique_together': {('liquidacion', 'anio_fiscal')},
            },
        ),
    ]
