# Generated by Django 6.0.3 on 2026-04-15 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasacartel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liquidacion',
            name='generado_por',
        ),
        migrations.AddField(
            model_name='liquidacion',
            name='generado_por_id_val',
            field=models.IntegerField(blank=True, db_column='generado_por_id', null=True, verbose_name='Generado por (user id)'),
        ),
    ]
