# Generated by Django 6.0.3 on 2026-04-18 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasacartel', '0002_remove_liquidacion_generado_por_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plandepago',
            name='cantidad_cuotas',
            field=models.PositiveIntegerField(help_text='Incluye la cuota 1, que vence al suscribir y no lleva interés.', verbose_name='Cantidad de cuotas'),
        ),
        migrations.AlterField(
            model_name='plandepago',
            name='monto_anticipo',
            field=models.DecimalField(decimal_places=2, help_text='Campo legado. Se conserva en cero por compatibilidad.', max_digits=14, verbose_name='Monto reservado ($)'),
        ),
        migrations.AlterField(
            model_name='plandepago',
            name='tasa_financiacion_mensual',
            field=models.DecimalField(decimal_places=4, help_text='Interés compuesto. Ej: 0.04 para 4% mensual.', max_digits=5, verbose_name='Tasa de financiación mensual (fracción)'),
        ),
    ]
