# Generated by Django 6.0.3 on 2026-04-10 18:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Parcela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('circunscripcion', models.CharField(blank=True, max_length=20, null=True)),
                ('seccion', models.CharField(blank=True, max_length=20, null=True)),
                ('chacra', models.CharField(blank=True, max_length=20, null=True)),
                ('parcela_nro', models.CharField(blank=True, max_length=20, null=True, verbose_name='Parcela')),
                ('direccion', models.CharField(blank=True, max_length=300, null=True)),
                ('localidad', models.CharField(blank=True, max_length=100, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Parcela',
                'verbose_name_plural': 'Parcelas',
                'ordering': ['circunscripcion', 'seccion', 'parcela_nro'],
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('fisica', 'Persona física'), ('juridica', 'Persona jurídica')], default='fisica', max_length=10)),
                ('apellido', models.CharField(blank=True, max_length=200, null=True)),
                ('nombre', models.CharField(blank=True, max_length=200, null=True)),
                ('razon_social', models.CharField(blank=True, help_text='Solo para personas jurídicas', max_length=300, null=True)),
                ('cuit_dni', models.CharField(help_text='CUIT para personas jurídicas, DNI para físicas', max_length=20, unique=True)),
                ('domicilio', models.CharField(blank=True, max_length=300, null=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'ordering': ['apellido', 'razon_social'],
            },
        ),
        migrations.CreateModel(
            name='Cartel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kobo_id', models.CharField(blank=True, help_text='ID único del registro en KoboToolbox (_id)', max_length=100, null=True, unique=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='carteles/fotos/')),
                ('tipo_foto', models.CharField(blank=True, max_length=100, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('tipo_ubicacion_gps', models.CharField(blank=True, max_length=50, null=True)),
                ('distancia', models.FloatField(blank=True, help_text='Distancia en metros entre el operador y el cartel', null=True)),
                ('tipo_cartel', models.CharField(blank=True, choices=[('publicitario', 'Publicitario'), ('politico', 'Político'), ('senalizacion', 'Señalización'), ('informativo', 'Informativo'), ('otro', 'Otro')], max_length=50, null=True)),
                ('estado_cartel', models.CharField(blank=True, choices=[('bueno', 'Bueno'), ('regular', 'Regular'), ('malo', 'Malo')], max_length=20, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(blank=True, help_text='Fecha de captura del formulario', null=True)),
                ('operador', models.CharField(blank=True, max_length=200, null=True)),
                ('cartel_detectado', models.BooleanField(blank=True, null=True)),
                ('confianza_deteccion', models.FloatField(blank=True, null=True)),
                ('bbox_x', models.IntegerField(blank=True, null=True)),
                ('bbox_y', models.IntegerField(blank=True, null=True)),
                ('bbox_w', models.IntegerField(blank=True, null=True)),
                ('bbox_h', models.IntegerField(blank=True, null=True)),
                ('ancho_m', models.FloatField(blank=True, null=True)),
                ('alto_m', models.FloatField(blank=True, null=True)),
                ('superficie_m2', models.FloatField(blank=True, null=True)),
                ('foto_anotada', models.ImageField(blank=True, null=True, upload_to='carteles/anotadas/')),
                ('texto_ocr', models.TextField(blank=True, null=True)),
                ('advertencia_sin_texto', models.BooleanField(default=False)),
                ('estado_procesamiento', models.CharField(choices=[('pendiente', 'Pendiente'), ('ok', 'Procesado OK'), ('error', 'Con errores')], default='pendiente', max_length=20)),
                ('estado_registro', models.CharField(choices=[('activo', 'Activo'), ('descartado', 'Descartado')], default='activo', max_length=20)),
                ('motivo_descarte', models.TextField(blank=True, null=True)),
                ('descartado_en', models.DateTimeField(blank=True, null=True)),
                ('error_sin_foto', models.BooleanField(default=False)),
                ('error_sin_deteccion', models.BooleanField(default=False)),
                ('error_distancia_invalida', models.BooleanField(default=False)),
                ('error_imagen_ilegible', models.BooleanField(default=False)),
                ('error_gps_invalido', models.BooleanField(default=False)),
                ('error_zoom_sospechoso', models.BooleanField(default=False)),
                ('detalle_error', models.TextField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('descartado_por', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carteles_descartados', to=settings.AUTH_USER_MODEL)),
                ('parcela', models.ForeignKey(blank=True, help_text='Parcela donde está instalado el cartel', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carteles', to='carteles.parcela')),
                ('propietario_cartel', models.ForeignKey(blank=True, help_text='Propietario del cartel (distinto al dueño del terreno)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carteles_propios', to='carteles.persona')),
            ],
            options={
                'verbose_name': 'Cartel',
                'verbose_name_plural': 'Carteles',
                'ordering': ['-creado'],
            },
        ),
        migrations.AddField(
            model_name='parcela',
            name='propietario_terreno',
            field=models.ForeignKey(blank=True, help_text='Propietario del terreno (distinto al dueño del cartel)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parcelas_propias', to='carteles.persona'),
        ),
        migrations.CreateModel(
            name='HistorialPublicidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_desde', models.DateField(blank=True, null=True)),
                ('fecha_hasta', models.DateField(blank=True, help_text='Vacío = publicita actualmente', null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('cartel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_publicidad', to='carteles.cartel')),
                ('empresa', models.ForeignKey(blank=True, help_text='Empresa o persona que publicita en el cartel', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publicidades', to='carteles.persona')),
            ],
            options={
                'verbose_name': 'Publicidad',
                'verbose_name_plural': 'Historial de publicidades',
                'ordering': ['-fecha_desde'],
            },
        ),
    ]
