# Generated by Django 6.0.3 on 2026-03-15 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cartel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kobo_id', models.CharField(blank=True, help_text='ID único del registro en KoboToolbox (_id)', max_length=100, null=True, unique=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='carteles/fotos/')),
                ('tipo_foto', models.CharField(blank=True, max_length=100, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('tipo_ubicacion_gps', models.CharField(blank=True, max_length=50, null=True)),
                ('distancia', models.FloatField(blank=True, help_text='Distancia en metros entre el operador y el cartel', null=True)),
                ('tipo_cartel', models.CharField(blank=True, choices=[('publicitario', 'Publicitario'), ('politico', 'Político'), ('senalizacion', 'Señalización'), ('informativo', 'Informativo'), ('otro', 'Otro')], max_length=50, null=True)),
                ('estado_cartel', models.CharField(blank=True, choices=[('bueno', 'Bueno'), ('regular', 'Regular'), ('malo', 'Malo')], max_length=20, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(blank=True, help_text='Fecha de captura del formulario', null=True)),
                ('operador', models.CharField(blank=True, help_text='Usuario que hizo la captura', max_length=200, null=True)),
                ('cartel_detectado', models.BooleanField(blank=True, help_text='True si YOLO encontró un cartel, False si no, None si no fue procesado', null=True)),
                ('confianza_deteccion', models.FloatField(blank=True, help_text='Score de confianza de YOLO (0-1)', null=True)),
                ('bbox_x', models.IntegerField(blank=True, null=True)),
                ('bbox_y', models.IntegerField(blank=True, null=True)),
                ('bbox_w', models.IntegerField(blank=True, null=True)),
                ('bbox_h', models.IntegerField(blank=True, null=True)),
                ('ancho_m', models.FloatField(blank=True, null=True)),
                ('alto_m', models.FloatField(blank=True, null=True)),
                ('superficie_m2', models.FloatField(blank=True, null=True)),
                ('foto_anotada', models.ImageField(blank=True, help_text='Foto con el bounding box dibujado', null=True, upload_to='carteles/anotadas/')),
                ('estado_procesamiento', models.CharField(choices=[('pendiente', 'Pendiente'), ('ok', 'Procesado OK'), ('error', 'Con errores')], default='pendiente', max_length=20)),
                ('error_sin_foto', models.BooleanField(default=False, help_text='El formulario fue importado sin foto adjunta')),
                ('error_sin_deteccion', models.BooleanField(default=False, help_text='YOLO no encontró ningún cartel en la imagen')),
                ('error_distancia_invalida', models.BooleanField(default=False, help_text='La distancia registrada es nula, cero o negativa')),
                ('error_imagen_ilegible', models.BooleanField(default=False, help_text='La imagen no pudo ser abierta o está corrupta')),
                ('error_gps_invalido', models.BooleanField(default=False, help_text='Las coordenadas GPS son nulas o inválidas')),
                ('detalle_error', models.TextField(blank=True, help_text='Descripción técnica del error ocurrido', null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cartel',
                'verbose_name_plural': 'Carteles',
                'ordering': ['-creado'],
            },
        ),
    ]
