# Generated by Django 6.0.3 on 2026-03-15 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carteles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartel',
            name='error_zoom_sospechoso',
            field=models.BooleanField(default=False, help_text='El cálculo sugiere que se usó zoom o la distancia es incorrecta'),
        ),
    ]
