# Generated by Django 6.0.3 on 2026-04-17 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carteles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartel',
            name='detalle_diagnostico',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cartel',
            name='diagnostico_geometria_inconsistente',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cartel',
            name='metodo_superficie',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
