# Generated by Django 6.0.3 on 2026-04-17 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carteles', '0002_cartel_detalle_diagnostico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartel',
            name='manual_esquinas',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cartel',
            name='origen_medicion',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
