# Generated by Django 6.0.3 on 2026-03-15 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carteles', '0002_cartel_error_zoom_sospechoso'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartel',
            name='advertencia_sin_texto',
            field=models.BooleanField(default=False, help_text='El OCR no encontró texto legible en el cartel'),
        ),
        migrations.AddField(
            model_name='cartel',
            name='texto_ocr',
            field=models.TextField(blank=True, help_text='Texto extraído del cartel por OCR (EasyOCR)', null=True),
        ),
    ]
