# Generated by Django 6.0.3 on 2026-03-15 21:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carteles', '0003_cartel_advertencia_sin_texto_cartel_texto_ocr'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cartel',
            name='descartado_en',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora del descarte', null=True),
        ),
        migrations.AddField(
            model_name='cartel',
            name='descartado_por',
            field=models.ForeignKey(blank=True, help_text='Usuario que descartó el registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carteles_descartados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cartel',
            name='estado_registro',
            field=models.CharField(choices=[('activo', 'Activo'), ('descartado', 'Descartado')], default='activo', help_text='Descartado: no aparece en listados ni reportes', max_length=20),
        ),
        migrations.AddField(
            model_name='cartel',
            name='motivo_descarte',
            field=models.TextField(blank=True, help_text='Motivo por el cual se descartó el registro', null=True),
        ),
    ]
