# Generated by Django 6.0.3 on 2026-03-15 22:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carteles', '0004_cartel_descartado_en_cartel_descartado_por_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Parcela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('circunscripcion', models.CharField(blank=True, max_length=20, null=True)),
                ('seccion', models.CharField(blank=True, max_length=20, null=True)),
                ('chacra', models.CharField(blank=True, max_length=20, null=True)),
                ('parcela_nro', models.CharField(blank=True, max_length=20, null=True, verbose_name='Parcela')),
                ('direccion', models.CharField(blank=True, max_length=300, null=True)),
                ('localidad', models.CharField(blank=True, max_length=100, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Parcela',
                'verbose_name_plural': 'Parcelas',
                'ordering': ['circunscripcion', 'seccion', 'parcela_nro'],
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('fisica', 'Persona física'), ('juridica', 'Persona jurídica')], default='fisica', max_length=10)),
                ('apellido', models.CharField(blank=True, max_length=200, null=True)),
                ('nombre', models.CharField(blank=True, max_length=200, null=True)),
                ('razon_social', models.CharField(blank=True, help_text='Solo para personas jurídicas', max_length=300, null=True)),
                ('cuit_dni', models.CharField(help_text='CUIT para personas jurídicas, DNI para físicas', max_length=20, unique=True)),
                ('domicilio', models.CharField(blank=True, max_length=300, null=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'ordering': ['apellido', 'razon_social'],
            },
        ),
        migrations.AlterField(
            model_name='cartel',
            name='advertencia_sin_texto',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cartel',
            name='cartel_detectado',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cartel',
            name='confianza_deteccion',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cartel',
            name='descartado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cartel',
            name='descartado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carteles_descartados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cartel',
            name='detalle_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cartel',
            name='error_distancia_invalida',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cartel',
            name='error_gps_invalido',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cartel',
            name='error_imagen_ilegible',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cartel',
            name='error_sin_deteccion',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cartel',
            name='error_sin_foto',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cartel',
            name='error_zoom_sospechoso',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cartel',
            name='estado_registro',
            field=models.CharField(choices=[('activo', 'Activo'), ('descartado', 'Descartado')], default='activo', max_length=20),
        ),
        migrations.AlterField(
            model_name='cartel',
            name='foto_anotada',
            field=models.ImageField(blank=True, null=True, upload_to='carteles/anotadas/'),
        ),
        migrations.AlterField(
            model_name='cartel',
            name='motivo_descarte',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cartel',
            name='operador',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cartel',
            name='texto_ocr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='HistorialPublicidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=300)),
                ('fecha_desde', models.DateField(blank=True, null=True)),
                ('fecha_hasta', models.DateField(blank=True, help_text='Vacío = publicita actualmente', null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('cartel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_publicidad', to='carteles.cartel')),
            ],
            options={
                'verbose_name': 'Publicidad',
                'verbose_name_plural': 'Historial de publicidades',
                'ordering': ['-fecha_desde'],
            },
        ),
        migrations.AddField(
            model_name='cartel',
            name='parcela',
            field=models.ForeignKey(blank=True, help_text='Parcela donde está instalado el cartel', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carteles', to='carteles.parcela'),
        ),
        migrations.AddField(
            model_name='parcela',
            name='propietario_terreno',
            field=models.ForeignKey(blank=True, help_text='Propietario del terreno (distinto al dueño del cartel)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parcelas_propias', to='carteles.persona'),
        ),
        migrations.AddField(
            model_name='cartel',
            name='propietario_cartel',
            field=models.ForeignKey(blank=True, help_text='Propietario del cartel (distinto al dueño del terreno)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carteles_propios', to='carteles.persona'),
        ),
    ]
