# Generated by Django 6.0.3 on 2026-03-26 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carteles', '0005_parcela_persona_alter_cartel_advertencia_sin_texto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialpublicidad',
            name='empresa',
            field=models.ForeignKey(blank=True, help_text='Empresa o persona que publicita en el cartel', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publicidades', to='carteles.persona'),
        ),
    ]
