# Generated by Django 6.0.3 on 2026-04-13 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasas_marchiquita', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deuda',
            name='deuda_original',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Deuda original sin intereses. Se llena cuando valor_total_deuda incluye intereses.', max_digits=14, null=True),
        ),
    ]
