# Generated by Django 6.0.3 on 2026-04-21 16:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, unique=True)),
                ('app_origen', models.CharField(help_text='Todas las líneas deben ser de la misma app', max_length=20)),
                ('fecha_emision', models.DateField()),
                ('fecha_cobro', models.DateField(blank=True, null=True)),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('estado', models.CharField(choices=[('PRESENTADA', 'Presentada'), ('COBRADA', 'Cobrada'), ('RECHAZADA', 'Rechazada'), ('ANULADA', 'Anulada')], default='PRESENTADA', max_length=15)),
                ('observaciones', models.TextField(blank=True)),
                ('archivo_pdf', models.BinaryField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'ordering': ['-fecha_emision'],
            },
        ),
        migrations.CreateModel(
            name='HonorarioLiquidacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_origen', models.CharField(choices=[('tasacartel', 'Tasa Cartel'), ('tasas_marchiquita', 'Tasas Marchiquita')], max_length=20)),
                ('tipo_origen', models.CharField(choices=[('CONTADO', 'Contado'), ('CUOTAS', 'Cuotas'), ('MARCHIQUITA', 'Tasas Marchiquita')], max_length=15)),
                ('liquidacion_tasacartel_id', models.IntegerField(blank=True, help_text='ID de tasacartel.Liquidacion', null=True)),
                ('liquidacion_marchiquita_id', models.IntegerField(blank=True, help_text='ID de tasas_marchiquita.Liquidacion', null=True)),
                ('periodo', models.DateField(help_text='Primer día del mes')),
                ('base_calculo', models.DecimalField(decimal_places=2, help_text='Monto cobrado sobre el que se aplica el porcentaje', max_digits=14)),
                ('porcentaje_aplicado', models.DecimalField(decimal_places=2, max_digits=5)),
                ('monto_honorario', models.DecimalField(decimal_places=2, max_digits=14)),
                ('generado_en', models.DateTimeField(auto_now_add=True)),
                ('generado_por', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='honorarios_generados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Honorario de liquidación',
                'verbose_name_plural': 'Honorarios de liquidación',
                'ordering': ['-periodo'],
            },
        ),
        migrations.CreateModel(
            name='HonorarioCuotaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuota_id', models.IntegerField(help_text='ID de tasacartel.Cuota')),
                ('monto_cuota', models.DecimalField(decimal_places=2, help_text='Snapshot del monto al momento de generar el honorario', max_digits=14)),
                ('honorario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuota_items', to='cobros_publivial.honorarioliquidacion')),
            ],
        ),
        migrations.CreateModel(
            name='FacturaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cobros_publivial.factura')),
                ('honorario', models.OneToOneField(help_text='Un honorario no puede aparecer en dos facturas', on_delete=django.db.models.deletion.PROTECT, related_name='factura_item', to='cobros_publivial.honorarioliquidacion')),
            ],
        ),
        migrations.CreateModel(
            name='ConfiguracionHonorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_origen', models.CharField(choices=[('tasacartel', 'Tasa Cartel'), ('tasas_marchiquita', 'Tasas Marchiquita')], max_length=20)),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=5)),
                ('vigente_desde', models.DateField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuración de honorario',
                'verbose_name_plural': 'Configuraciones de honorario',
                'ordering': ['app_origen', '-vigente_desde'],
                'unique_together': {('app_origen', 'vigente_desde')},
            },
        ),
        migrations.AddConstraint(
            model_name='honorarioliquidacion',
            constraint=models.UniqueConstraint(condition=models.Q(('liquidacion_marchiquita_id__isnull', False)), fields=('liquidacion_marchiquita_id',), name='unique_honorario_marchiquita'),
        ),
        migrations.AddConstraint(
            model_name='honorarioliquidacion',
            constraint=models.UniqueConstraint(condition=models.Q(('liquidacion_tasacartel_id__isnull', False), ('tipo_origen', 'CONTADO')), fields=('liquidacion_tasacartel_id', 'tipo_origen'), name='unique_honorario_tasacartel_contado'),
        ),
        migrations.AlterUniqueTogether(
            name='honorariocuotaitem',
            unique_together={('honorario', 'cuota_id')},
        ),
    ]
