# Generated by Django 6.0.3 on 2026-03-05 18:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Parcela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_inmueble', models.CharField(max_length=50)),
                ('circuns', models.CharField(blank=True, max_length=50, verbose_name='Circunscripción')),
                ('fraccion_nro', models.CharField(blank=True, max_length=50)),
                ('parcela_nro', models.CharField(blank=True, max_length=50)),
                ('parcela_let', models.CharField(blank=True, max_length=10)),
                ('subparcela', models.CharField(blank=True, max_length=50)),
                ('uni_funcional', models.CharField(blank=True, max_length=50, verbose_name='Unidad funcional')),
                ('par_catastral', models.CharField(blank=True, max_length=100, verbose_name='Parcela catastral')),
                ('sup_terreno', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Superficie terreno (m²)')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Parcela',
                'verbose_name_plural': 'Parcelas',
                'ordering': ['nro_inmueble'],
            },
        ),
        migrations.CreateModel(
            name='ResponsablePago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resp_pago', models.CharField(help_text='Valor del campo RESP_PAGO del Excel', max_length=100, unique=True)),
                ('nombre', models.CharField(blank=True, max_length=255)),
                ('documento', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=50)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Responsable de pago',
                'verbose_name_plural': 'Responsables de pago',
                'ordering': ['resp_pago'],
            },
        ),
        migrations.CreateModel(
            name='ArchivoImportacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.BinaryField()),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('periodo', models.DateField(help_text='Primer día del mes al que corresponde. Ej: 2024-03-01')),
                ('importado_en', models.DateTimeField(auto_now_add=True)),
                ('total_registros', models.PositiveIntegerField(default=0)),
                ('observaciones', models.TextField(blank=True)),
                ('procesado', models.BooleanField(default=False, help_text='Indica si el archivo ya fue procesado e incorporado a la BD')),
                ('importado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='importaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Archivo de importación',
                'verbose_name_plural': 'Archivos de importación',
                'ordering': ['-periodo'],
                'unique_together': {('periodo',)},
            },
        ),
        migrations.CreateModel(
            name='Deuda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_total_deuda', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='VALOR TOTAL_DEUDA')),
                ('pago_total_deuda', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='PAGO_TOTAL_DEUDA')),
                ('tiene_plan_cuotas', models.BooleanField(default=False, verbose_name='PLAN DE CUOTAS')),
                ('anticipo', models.DecimalField(blank=True, decimal_places=2, help_text='Anticipo en efectivo del plan', max_digits=14, null=True)),
                ('cantidad_cuotas', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='CANTIDAD DE CUOTAS')),
                ('estado', models.CharField(choices=[('VIGENTE', 'Vigente'), ('EN_PLAN', 'En plan de cuotas'), ('CANCELADA', 'Cancelada')], default='VIGENTE', max_length=10)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('importacion', models.ForeignKey(help_text='Archivo del que proviene este estado', on_delete=django.db.models.deletion.PROTECT, related_name='deudas', to='principal.archivoimportacion')),
                ('parcela', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deudas', to='principal.parcela')),
            ],
            options={
                'verbose_name': 'Deuda',
                'verbose_name_plural': 'Deudas',
                'ordering': ['-importacion__periodo', 'parcela'],
                'unique_together': {('parcela', 'importacion')},
            },
        ),
        migrations.AddField(
            model_name='parcela',
            name='responsable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parcelas', to='principal.responsablepago'),
        ),
        migrations.CreateModel(
            name='Cuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cuota', models.PositiveSmallIntegerField(verbose_name='NUMERO_DE_CUOTA_PAGADA')),
                ('monto_pagado', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='MONTO_PAGADO')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGA', 'Paga'), ('VENCIDA', 'Vencida')], default='PAGA', max_length=10)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('importacion', models.ForeignKey(help_text='Archivo en el que se registró este pago', on_delete=django.db.models.deletion.PROTECT, related_name='cuotas', to='principal.archivoimportacion')),
                ('deuda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuotas', to='principal.deuda')),
            ],
            options={
                'verbose_name': 'Cuota',
                'verbose_name_plural': 'Cuotas',
                'ordering': ['deuda', 'numero_cuota'],
                'unique_together': {('deuda', 'numero_cuota')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='parcela',
            unique_together={('nro_inmueble', 'circuns', 'fraccion_nro', 'parcela_nro', 'parcela_let', 'subparcela')},
        ),
    ]
