# Generated by Django 6.0.3 on 2026-03-06 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='archivoimportacion',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='archivoimportacion',
            name='reemplazado_por',
            field=models.ForeignKey(blank=True, help_text='Archivo corregido que reemplaza a este', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reemplaza_a', to='principal.archivoimportacion'),
        ),
        migrations.AddField(
            model_name='archivoimportacion',
            name='revertido',
            field=models.BooleanField(default=False, help_text='Indica si el procesamiento fue revertido'),
        ),
        migrations.AlterUniqueTogether(
            name='archivoimportacion',
            unique_together={('periodo', 'revertido')},
        ),
    ]
