# Generated by Django 6.0.3 on 2026-03-06 20:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_alter_archivoimportacion_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Liquidacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_pago_deuda', models.DecimalField(decimal_places=2, help_text='Suma de PAGO_TOTAL_DEUDA del período', max_digits=14)),
                ('total_anticipos', models.DecimalField(decimal_places=2, help_text='Suma de anticipos del período', max_digits=14)),
                ('total_cuotas', models.DecimalField(decimal_places=2, help_text='Suma de montos de cuotas pagadas del período', max_digits=14)),
                ('total_cobrado', models.DecimalField(decimal_places=2, help_text='Suma total cobrada (pago + anticipos + cuotas)', max_digits=14)),
                ('comision', models.DecimalField(decimal_places=2, help_text='25% del total cobrado', max_digits=14)),
                ('pdf', models.BinaryField(blank=True, help_text='PDF de la liquidación generado', null=True)),
                ('generada_en', models.DateTimeField(auto_now_add=True)),
                ('generada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liquidaciones', to=settings.AUTH_USER_MODEL)),
                ('importacion', models.OneToOneField(help_text='Archivo procesado sobre el que se calcula la liquidación', on_delete=django.db.models.deletion.PROTECT, related_name='liquidacion', to='principal.archivoimportacion')),
            ],
            options={
                'verbose_name': 'Liquidación',
                'verbose_name_plural': 'Liquidaciones',
                'ordering': ['-importacion__periodo'],
            },
        ),
    ]
